/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Lucho
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form PanelPrincipal
     */
    public Login() {
        initComponents();
        //------STYLE CSS-----------------
        StyleCSS.setPlaceHolder(fieldUser, "usuario");
        StyleCSS.setPlaceHolder(fielPass, "password");
        //-----------------
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icono = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fieldUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fielPass = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Captura.PNG"))); // NOI18N
        add(icono);
        icono.setBounds(20, 30, 610, 270);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Usuario:");
        add(jLabel1);
        jLabel1.setBounds(250, 310, 51, 14);
        add(fieldUser);
        fieldUser.setBounds(250, 330, 220, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Contraseña:");
        add(jLabel2);
        jLabel2.setBounds(250, 390, 68, 14);

        jButton1.setText("Ingresar");
        add(jButton1);
        jButton1.setBounds(280, 470, 146, 34);
        add(fielPass);
        fielPass.setBounds(250, 410, 220, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField fielPass;
    private javax.swing.JTextField fieldUser;
    private javax.swing.JLabel icono;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
